#pragma once

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP26
#define SPI_MOSI_PIN GP27
#define SPI_MISO_PIN GP28
#define PMW33XX_CS_PIN GP29

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#undef DYNAMIC_KEYMAP_MACRO_COUNT
#define DYNAMIC_KEYMAP_MACRO_COUNT 0

#define POINTING_DEVICE_INVERT_X

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
/* DPI 1000, scroll 1/48, drag DPI off, drag DPI 500, 3 buttons, right handed */
#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x00009D48
