MCU = RP2040
BOARD = GENERIC_RP_RP2040
BOOTLOADER = rp2040
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389

VIA_ENABLE = yes

NKRO_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
CAPS_WORD_ENABLE = no
REPEAT_KEY_ENABLE = no
AUTO_SHIFT_ENABLE = no
QMK_SETTINGS = no
DYNAMIC_KEYMAP_ENABLE = yes
